version: '3.4'

services:
  blockchain:
    image: ${DOCKER_REGISTRY-}blockchain
    build:
      context: .
      dockerfile: Blockchain\Dockerfile
    networks:
      hostserver:
        ipv4_address: 192.168.0.2

  client1:
    image: ${DOCKER_REGISTRY-}blockchain
    networks:
      hostserver:
        ipv4_address: 192.168.0.4

  client2:
    image: ${DOCKER_REGISTRY-}blockchain
    networks:
      hostserver:
        ipv4_address: 192.168.0.6

  client3:
    image: ${DOCKER_REGISTRY-}blockchain
    networks:
      hostserver:
        ipv4_address: 192.168.0.8

networks:
  hostserver:
    ipam:
      config:
        - subnet: 192.168.0.0/16