version: '3.4'

services:
  blockchain:
    image: ${DOCKER_REGISTRY-}blockchain
    build:
      context: .
      dockerfile: Blockchain\Dockerfile

  nginx:
    image: nginx
    container_name: nginx-container_name
    networks:
      static-network:
        ipv4_address: 192.10.1.1

networks:
  static-network:
    ipam:
      config:
        - subnet: 192.10.0.0/16