version: '3.4'

services:
  blockchain:   
    image: ${DOCKER_REGISTRY-}blockchain
    build:
      context: .
      dockerfile: Blockchain/Dockerfile   
    container_name: client4_1
    ports:
      - "8080:2222"

  client1:
    image: ${DOCKER_REGISTRY-}blockchain
    ports:
      - "8081:2222"

  client2:
    image: ${DOCKER_REGISTRY-}blockchain
    ports:
      - "8082:2222"

  client3:
    image: ${DOCKER_REGISTRY-}blockchain
    ports:
      - "8083:2222"