version: '3.4'

services:
  blockchain:   
    image: ${DOCKER_REGISTRY-}blockchain
    build:
      context: .
      dockerfile: Blockchain/Dockerfile   
    container_name: client4_1
    ports:
      - "2222:80"

  client1:
    image: ${DOCKER_REGISTRY-}blockchain
    build:
      context: .
      dockerfile: Blockchain/Dockerfile
    ports:
      - "2222:80"

  client2:
    image: ${DOCKER_REGISTRY-}blockchain
    build:
      context: .
      dockerfile: Blockchain/Dockerfile
    ports:
      - "2222:80"


  client3:
    image: ${DOCKER_REGISTRY-}blockchain
    build:
      context: .
      dockerfile: Blockchain/Dockerfile
    ports:
      - "2222:80"